"""
Financial Event Model
---------------------
Every action in Assurance is an event — something that happened
at a specific time, to a specific financial entity.

We never store only the final state ("payment = failed").
We store what happened + when + where + to what entity.
That's what lets us reconstruct causality later.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from pydantic import BaseModel, Field, field_validator
import uuid


# ---------------------------------------------------------------------------
# Event Types
# ---------------------------------------------------------------------------

class EventType(str, Enum):
    # Payment lifecycle
    PAYMENT_CREATED      = "payment.created"
    PAYMENT_AUTHORIZED   = "payment.authorized"
    PAYMENT_CAPTURED     = "payment.captured"
    PAYMENT_FAILED       = "payment.failed"
    PAYMENT_TIMEOUT      = "payment.timeout"
    PAYMENT_CANCELLED    = "payment.cancelled"

    # Retry lifecycle
    RETRY_INITIATED      = "retry.initiated"
    RETRY_SUCCEEDED      = "retry.succeeded"
    RETRY_FAILED         = "retry.failed"

    # Refund lifecycle
    REFUND_REQUESTED     = "refund.requested"
    REFUND_PROCESSED     = "refund.processed"
    REFUND_FAILED        = "refund.failed"
    REFUND_REVERSED      = "refund.reversed"
    REFUND_COMPLETED     = "refund.completed"

    # Settlement lifecycle
    SETTLEMENT_CREATED   = "settlement.created"
    SETTLEMENT_PROCESSED = "settlement.processed"
    SETTLEMENT_ADJUSTED  = "settlement.adjusted"
    SETTLEMENT_FAILED    = "settlement.failed"

    # Dispute lifecycle
    DISPUTE_CREATED              = "dispute.created"
    DISPUTE_EVIDENCE_SUBMITTED   = "dispute.evidence_submitted"
    DISPUTE_ACCEPTED             = "dispute.accepted"
    DISPUTE_REJECTED             = "dispute.rejected"
    DISPUTE_CLOSED               = "dispute.closed"

    # Autonomous agent actions — crucial for causal reconstruction
    AGENT_RETRY_INITIATED    = "agent.retry_initiated"
    AGENT_REFUND_INITIATED   = "agent.refund_initiated"
    AGENT_DISPUTE_INITIATED  = "agent.dispute_initiated"


class EventSource(str, Enum):
    GATEWAY       = "gateway"
    BANK          = "bank"
    AGENT         = "agent"          # Autonomous recovery/retry agent
    MERCHANT      = "merchant"
    CUSTOMER      = "customer"
    RAZORPAY      = "razorpay"
    ASSURANCE     = "assurance"      # Events generated by Assurance itself


# ---------------------------------------------------------------------------
# Core Event Model
# ---------------------------------------------------------------------------

class FinancialEvent(BaseModel):
    """
    A single atomic event in the financial system.

    Design principle: store what happened, not what we think the state is.
    State is derived by the state engine from this stream of events.
    """

    event_id:    str      = Field(default_factory=lambda: f"evt_{uuid.uuid4().hex[:8]}")
    event_type:  EventType
    timestamp:   datetime
    source:      EventSource

    # Entity identifiers — not all will be present for every event
    merchant_id:  Optional[str] = None
    customer_id:  Optional[str] = None
    order_id:     Optional[str] = None
    payment_id:   Optional[str] = None
    refund_id:    Optional[str] = None
    dispute_id:   Optional[str] = None
    settlement_id: Optional[str] = None

    # Financial fields
    amount:   Optional[int] = None    # Always in paise (1 INR = 100 paise)
    currency: str = "INR"

    # Causal linkage — what prior event caused this one?
    # This is filled by the agent or gateway when they know the cause.
    # The causal graph engine also infers links when this is absent.
    caused_by_event_id: Optional[str] = None

    # Arbitrary metadata for evidence
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("timestamp")
    @classmethod
    def normalize_timestamp(cls, value: datetime) -> datetime:
        """Store every event timestamp as timezone-aware UTC."""
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc)

    class Config:
        use_enum_values = True

    @property
    def amount_inr(self) -> Optional[float]:
        """Convenience: amount in rupees (events store paise internally)."""
        if self.amount is None:
            return None
        return self.amount / 100

    def __repr__(self) -> str:
        ts = self.timestamp.strftime("%H:%M:%S")
        amt = f" ₹{self.amount_inr:,.0f}" if self.amount else ""
        return f"[{ts}] {self.event_type}{amt} ({self.payment_id or self.refund_id or self.order_id or ''})"


# ---------------------------------------------------------------------------
# Event Stream — ordered collection of events for a given scope
# ---------------------------------------------------------------------------

class EventStream(BaseModel):
    """
    An ordered, append-only stream of financial events for a single scope
    (e.g., one order, or one merchant over a time window).

    The state engine and causal graph both consume EventStreams.
    """

    stream_id:  str = Field(default_factory=lambda: f"stream_{uuid.uuid4().hex[:8]}")
    order_id:   Optional[str] = None
    merchant_id: Optional[str] = None
    events:     list[FinancialEvent] = Field(default_factory=list)

    def add(self, event: FinancialEvent) -> None:
        self.events.append(event)
        self.events.sort(key=lambda e: e.timestamp)

    def by_type(self, *event_types: EventType) -> list[FinancialEvent]:
        types = {et.value if hasattr(et, 'value') else et for et in event_types}
        return [e for e in self.events if e.event_type in types]

    def for_payment(self, payment_id: str) -> list[FinancialEvent]:
        return [e for e in self.events if e.payment_id == payment_id]

    def for_refund(self, refund_id: str) -> list[FinancialEvent]:
        return [e for e in self.events if e.refund_id == refund_id]

    @property
    def payment_ids(self) -> list[str]:
        return list(dict.fromkeys(
            e.payment_id for e in self.events if e.payment_id
        ))

    @property
    def refund_ids(self) -> list[str]:
        return list(dict.fromkeys(
            e.refund_id for e in self.events if e.refund_id
        ))

    def __len__(self) -> int:
        return len(self.events)

    def __iter__(self):
        return iter(self.events)
